spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/caffe_bar
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      initialization-mode: always
